version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: curve
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    volumes:
      - .:/go/src/github.com/andream16/curve-challenge
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db